# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04grpc\"\x07\n\x05\x45mpty\"\xa1\x01\n\x04Mssg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08userType\x18\x02 \x01(\t\x12\x11\n\teventType\x18\x03 \x01(\t\x12\x11\n\teventName\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\x11\n\ttimeSlots\x18\x06 \x01(\t\x12\x12\n\nactivities\x18\x07 \x01(\t\x12\x0f\n\x07message\x18\x08 \x01(\t\x12\r\n\x05other\x18\t \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t2\xdd\x01\n\nChatServer\x12(\n\nChatStream\x12\x0c.grpc.Number\x1a\n.grpc.Mssg0\x01\x12(\n\nEventCheck\x12\x0c.grpc.Number\x1a\n.grpc.Mssg0\x01\x12&\n\x08SendMssg\x12\n.grpc.Mssg\x1a\x0e.grpc.Response\x12\'\n\rRequestAccess\x12\n.grpc.Mssg\x1a\n.grpc.Mssg\x12*\n\x0cOpenRequests\x12\x0c.grpc.Number\x1a\n.grpc.Mssg0\x01\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_MSSG = DESCRIPTOR.message_types_by_name['Mssg']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_NUMBER = DESCRIPTOR.message_types_by_name['Number']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

Mssg = _reflection.GeneratedProtocolMessageType('Mssg', (_message.Message,), {
  'DESCRIPTOR' : _MSSG,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Mssg)
  })
_sym_db.RegisterMessage(Mssg)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Response)
  })
_sym_db.RegisterMessage(Response)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Number)
  })
_sym_db.RegisterMessage(Number)

_CHATSERVER = DESCRIPTOR.services_by_name['ChatServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _MSSG._serialized_start=30
  _MSSG._serialized_end=191
  _RESPONSE._serialized_start=193
  _RESPONSE._serialized_end=220
  _NUMBER._serialized_start=222
  _NUMBER._serialized_end=259
  _CHATSERVER._serialized_start=262
  _CHATSERVER._serialized_end=483
# @@protoc_insertion_point(module_scope)
