# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_pb2 as chat__pb2


class ChatServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatStream = channel.unary_stream(
                '/grpc.ChatServer/ChatStream',
                request_serializer=chat__pb2.Number.SerializeToString,
                response_deserializer=chat__pb2.Mssg.FromString,
                )
        self.EventCheck = channel.unary_stream(
                '/grpc.ChatServer/EventCheck',
                request_serializer=chat__pb2.Number.SerializeToString,
                response_deserializer=chat__pb2.Mssg.FromString,
                )
        self.SendMssg = channel.unary_unary(
                '/grpc.ChatServer/SendMssg',
                request_serializer=chat__pb2.Mssg.SerializeToString,
                response_deserializer=chat__pb2.Response.FromString,
                )
        self.RequestAccess = channel.unary_unary(
                '/grpc.ChatServer/RequestAccess',
                request_serializer=chat__pb2.Mssg.SerializeToString,
                response_deserializer=chat__pb2.Mssg.FromString,
                )
        self.OpenRequests = channel.unary_stream(
                '/grpc.ChatServer/OpenRequests',
                request_serializer=chat__pb2.Number.SerializeToString,
                response_deserializer=chat__pb2.Mssg.FromString,
                )


class ChatServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChatStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMssg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=chat__pb2.Number.FromString,
                    response_serializer=chat__pb2.Mssg.SerializeToString,
            ),
            'EventCheck': grpc.unary_stream_rpc_method_handler(
                    servicer.EventCheck,
                    request_deserializer=chat__pb2.Number.FromString,
                    response_serializer=chat__pb2.Mssg.SerializeToString,
            ),
            'SendMssg': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMssg,
                    request_deserializer=chat__pb2.Mssg.FromString,
                    response_serializer=chat__pb2.Response.SerializeToString,
            ),
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=chat__pb2.Mssg.FromString,
                    response_serializer=chat__pb2.Mssg.SerializeToString,
            ),
            'OpenRequests': grpc.unary_stream_rpc_method_handler(
                    servicer.OpenRequests,
                    request_deserializer=chat__pb2.Number.FromString,
                    response_serializer=chat__pb2.Mssg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.ChatServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ChatServer/ChatStream',
            chat__pb2.Number.SerializeToString,
            chat__pb2.Mssg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EventCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ChatServer/EventCheck',
            chat__pb2.Number.SerializeToString,
            chat__pb2.Mssg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMssg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ChatServer/SendMssg',
            chat__pb2.Mssg.SerializeToString,
            chat__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.ChatServer/RequestAccess',
            chat__pb2.Mssg.SerializeToString,
            chat__pb2.Mssg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OpenRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.ChatServer/OpenRequests',
            chat__pb2.Number.SerializeToString,
            chat__pb2.Mssg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
